HOSTS:
  el7-build-server:
    roles:
      - default
      - build_server
    platform: el-7-x86_64
    hypervisor: docker
    image: simpproject/simp_build_centos7
    docker_cmd: '/usr/sbin/sshd -D -E /var/log/sshd.log'

  el8-build-server:
    roles:
      - build_server
    platform: el-8-x86_64
    hypervisor: docker
    image: simpproject/simp_build_centos8
    docker_cmd: '["/sbin/init"]'
    docker_preserve_image: true

CONFIG:
  log_level: verbose
  type:      aio
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% else -%>
  puppet_collection: puppet6
<% end -%>
  ssh:
    password: root
    auth_methods:
      - password
  docker_preserve_image: true
  # This is necessary for pretty much all containers
  docker_cap_add:
    - AUDIT_WRITE
  mount_folders:
    host_files:
      host_path: ./
      container_path: /host_files
  # All items below this point are required for systemd
    cgroup:
      host_path: /sys/fs/cgroup
      container_path: /sys/fs/cgroup
      opts: 'ro'
  dockeropts:
    HostConfig:
      Tmpfs:
        '/run': 'rw,noexec,nosuid,nodev,size=65536k'
        '/run/lock': 'rw,noexec,nosuid,nodev,size=65536k'
        '/tmp': 'rw,exec,nosuid,nodev,size=65536k'
        '/sys/fs/cgroup/systemd': 'rw,size=65536k'
        '/var/log/journal': 'rw,noexec,nodev,nosuid,size=65536k'
